Repository AswinTorch/TTP-Capstone-Project-Client, pull requests merged in 2020-06, with the labels that each got.

#14 Add courses to enrolled courses list and add course list
  package-lock.json
  package.json
  src/view/Enrollment/CourseListView.jsx
  src/view/Enrollment/EnrolledCoursesView.jsx
  src/view/Enrollment/EnrollmentView.jsx
Labels: enhancement

#22 Compartmentalize existing enrollment components into smaller reusable pieces
  src/view/Dashboard/DashboardView.jsx
  src/view/Enrollment/CourseList/CourseListContainer.jsx
  src/view/Enrollment/CourseList/CourseListItem.jsx
  src/view/Enrollment/CourseList/CourseListView.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCourseItem.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCoursesContainer.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCoursesView.jsx
  src/view/Enrollment/EnrollmentContainer.jsx
  src/view/Enrollment/EnrollmentView.jsx
Labels: documentation, enhancement

#31 User registration implementation, connected to database
  src/view/App/App.js
Labels: enhancement

#58 Enroll button hotfix
  src/view/Enrollment/CourseList/CourseListItem.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCourseItem.jsx
Labels: bug, enhancement

#59 Added swap modal component, redesigned enrollment and course list card views, and added logic for enroll and swap button rendering
  src/view/Enrollment/CourseList/CourseListItem.jsx
  src/view/Enrollment/CourseList/CourseListView.jsx
  src/view/Enrollment/CourseList/SwapCourseView.js
  src/view/Enrollment/EnrolledCourses/EnrolledCourseItem.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCoursesView.jsx
  src/view/Enrollment/EnrollmentView.jsx
  src/view/Navbar/NotificationsToggleMenu.js
  src/view/Navbar/UserToggleMenu.js
Labels: enhancement

#61 Added null/error checks to enrolled courses view
  src/view/Enrollment/CourseList/CourseListItem.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCoursesView.jsx
Labels: bug

#66 Fixed errors with course list and enrolled courses not displaying alt…
  src/view/Enrollment/CourseList/CourseListItem.jsx
  src/view/Enrollment/CourseList/CourseListView.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCoursesView.jsx
Labels: bug

#68 Add transaction history for actions
  package.json
  src/state/enrollment/reducers.js
  src/state/enrollment/thunks.js
  src/state/finance/action_types.js
  src/state/finance/actions.js
  src/view/Finance/FinanceDetails/FinanceDetailsContainer.jsx
  src/view/Finance/FinanceDetails/FinanceDetailsItem.jsx
  src/view/Finance/FinanceDetails/FinanceDetailsView.jsx
  src/view/Finance/FinanceView.jsx
Labels: enhancement

#74 Ui fixes
  src/view/App/App.css
  src/view/App/App.js
  src/view/Enrollment/CourseList/CourseListContainer.jsx
  src/view/Enrollment/Professor/ProfessorView.css
  src/view/Enrollment/Professor/ProfessorView.jsx
  src/view/Finance/FinanceOverview/MoneyOwedView.jsx
  src/view/Login/LoginView.jsx
  src/view/Navbar/NotificationsToggleMenu.js
  src/view/SideMenu/SideMenuView.jsx
Labels: bug

#75 State refactor
  src/view/App/App.js
  src/view/Dashboard/DashboardContainer.jsx
  src/view/Enrollment/CourseList/CourseListContainer.jsx
  src/view/Enrollment/EnrolledCourses/EnrolledCoursesContainer.jsx
  src/view/Enrollment/EnrollmentContainer.jsx
  src/view/Finance/FinanceContainer.jsx
  src/view/Finance/FinanceDetails/FinanceDetailsContainer.jsx
  src/view/Finance/FinanceDetails/FinanceDetailsItem.jsx
  src/view/Finance/FinanceDetails/FinanceDetailsView.jsx
  src/view/Finance/FinanceOverview/MoneyOwedContainer.jsx
  src/view/Routes/RoutesContainer.jsx
  src/view/Routes/RoutesView.jsx
  src/view/SideMenu/SideMenuContainer.jsx
Labels: enhancement

#76 Added typescript module and config file
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#79 Fixed container refactor issue in Dashboard and added empty ts file t…
  src/react-app-env.d.ts
  src/view/Dashboard/Dashboard.jsx
  src/view/Finance/FinanceOverview/MoneyOwed.jsx
  test.ts
  tsconfig.json
Labels: enhancement
